[project]
name = "boardgame"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest>=8.4.1",
]

[tool.pytest]
addopts = "-q"

[project.optional-dependencies]
dev = ["pytest>=7.0"]
